<a href="https://colab.research.google.com/github/Lil0nly2/DataScience/blob/main/python_analysis_Pandas%26Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Python Analysis Stack: NumPy & pandas Masterclass
### A Step-by-Step, Foundational  Guide for Scientific Computing & Data Analysis

Welcome to **The Python Analysis Stack Masterclass**! This notebook is specifically engineered as a clear, step-by-step  resource covering ** foundations** of **NumPy** and **pandas** — the two foundational engines powering modern data science, business analytics, and machine learning in Python.

---

## Notebook Roadmap
1. **Module 1: NumPy Foundations (Array Computing)**
   - **1.1 Why NumPy?** (Speed)
   - **1.2 Array Creation Routines** (`np.array`, `zeros`, `ones`, `full`, `arange`, `linspace`, `default_rng`)
   - **1.3 Array Inspection & Data Types** (`ndim`, `shape`, `size`, `dtype`, `astype`)
   - **1.4 Indexing & Multi-Dimensional Slicing** (1D, 2D matrices, strides, submatrices)
   - **1.5 The Golden Rule: Views vs. Copies** (Memory reference pitfall & `.copy()`)
   - **1.6 Boolean Indexing & Conditional Filtering** (Bitwise masks, `&`, `|`, `~`, `np.where`)
   - **1.7 Fancy Indexing** (Integer array indexing)
   - **1.8 Vectorized Operations & Universal Functions (UFuncs)**
   - **1.9 Broadcasting Mechanics** (The 2 Rules of Shape Compatibility)
   - **1.10 Aggregations & Axis-Wise Reductions** (`axis=0` vs. `axis=1`, `sum`, `mean`, `argmin`, `cumsum`)
   - **1.11 Shape Manipulation, Stacking & Splitting** (`reshape`, `ravel`, `flatten`, `.T`, `vstack`, `hstack`)

2. **Module 2: pandas Foundations (Tabular Data Analysis)**
   - **2.1 Why pandas?** (Labeled tabular structures vs. raw arrays)
   - **2.2 The 1D Building Block: pandas Series** (Values, index, alignment, operations)
   - **2.3 Creating DataFrames** (From dicts of lists, lists of dicts, and 2D arrays)
   - **2.4 Data Exploration & Inspection Checklist** (`head`, `tail`, `shape`, `info`, `describe`, `value_counts`)
   - **2.5 Indexing & Selection Trifecta** (`[]`, `.loc` label-based vs. `.iloc` integer-based)
   - **2.6 Conditional Filtering & Querying** (Multi-condition logic, `.isin()`, `.between()`, `.query()`)
   - **2.7 Modifying DataFrames** (Feature engineering, `.rename()`, `.drop()`, `.set_index()`, `.reset_index()`)
   - **2.8 Handling Missing Data** (`isna()`, `dropna()`, `fillna()`, forward/backward fill)
   - **2.9 GroupBy & Aggregations** (Split-Apply-Combine paradigm, multi-column grouping, `.agg()`)
   - **2.10 Combining Datasets** (`pd.concat` stacking vs. `pd.merge` relational SQL joins)
   - **2.11 Sorting & Ranking** (`sort_values()`, multi-column sort, `sort_index()`, `.rank()`)
   - **2.12 Essential String & Datetime Foundations** (`.str` and `.dt` accessors)
   - **2.13 File Input / Output** (Exporting and loading CSV files safely)

3. **Module 3: Guided Capstone Project**
   - An end-to-end retail store dataset synthesized, cleaned, analyzed, and summarized using NumPy + pandas.

4. **Module 4: Summary & Quick Reference Cheat Sheet**
   - Complete lookup tables for quick recall during projects and interviews.

---

### Step 0: Environment Setup & Library Imports
Standard industry conventions import **NumPy** as `np` and **pandas** as `pd`.

In [2]:
import numpy as np
import pandas as pd
import time

---
# Module 1: NumPy Foundations

**NumPy** (Numerical Python) is the foundational linear algebra and array-computing library of the Python data science ecosystem.

### Core Mental Model:
- **Homogeneous Data**: Every element in a NumPy array must share the identical data type (`dtype`).

### 1.1 Why NumPy? Speed & Vectorization Benchmark
Let's compare squaring 1,000,000 numbers using standard Python lists versus a NumPy `ndarray`.

In [12]:
N = 1_000_000

# 1. Pure Python approach with list comprehension
py_list = list(range(N))
t0 = time.perf_counter()
print(t0)
py_result = [x ** 2 for x in py_list]
py_time = time.perf_counter() - t0

# 2. NumPy vectorized approach
np_arr = np.arange(N)
print(np_arr)
t0 = time.perf_counter()
np_result = np_arr ** 2
np_time = time.perf_counter() - t0

print(f"Pure Python List time: {py_time:.5f} seconds")
print(f"NumPy Array time:      {np_time:.5f} seconds")
print(f"NumPy is approx {py_time / np_time:.1f}x faster!")

2571.837845655
[     0      1      2 ... 999997 999998 999999]
Pure Python List time: 0.35618 seconds
NumPy Array time:      0.01016 seconds
NumPy is approx 35.1x faster!


### 1.2 Array Creation Routines
NumPy offers built-in constructor functions to initialize arrays without writing loops.

| Function | Purpose | Example |
| :--- | :--- | :--- |
| `np.array()` | Converts a Python list or nested list into an array | `np.array([1, 2, 3])` |
| `np.zeros(shape)` | Fills array with `0.0` | `np.zeros((2, 3))` |
| `np.ones(shape)` | Fills array with `1.0` | `np.ones((3, 3))` |
| `np.full(shape, val)` | Fills array with custom constant | `np.full((2, 2), 7.5)` |
| `np.eye(N)` | Creates an $N \times N$ Identity Matrix | `np.eye(3)` |
| `np.arange(start, stop, step)` | Generates range with step size (exclusive stop) | `np.arange(0, 10, 2)` |
| `np.linspace(start, stop, num)` | Generates `num` evenly spaced points (inclusive stop) | `np.linspace(0, 1, 5)` |
| `np.random.default_rng()` | Modern random number generator | `rng.standard_normal((2, 3))` |

In [16]:
# Creating 1D and 2D arrays from Python lists
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:\n", arr_1d)
print("\n2D Array (Matrix):\n", arr_2d)

1D Array:
 [10 20 30 40 50]

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]


In [17]:
# Built-in array initializers
zeros = np.zeros(shape=(2, 4))
ones = np.ones(shape=(3, 3))
constants = np.full(shape=(2, 3), fill_value=9.9)
identity = np.eye(3)

print("Zeros (2x4):\n", zeros)
print("\nOnes (3x3):\n", ones)
print("\nFull with 9.9 (2x3):\n", constants)
print("\nIdentity Matrix (3x3):\n", identity)

Zeros (2x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (3x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full with 9.9 (2x3):
 [[9.9 9.9 9.9]
 [9.9 9.9 9.9]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Numerical Ranges: arange vs. linspace
# np.arange(start, stop, step) - step-based (stop is EXCLUSIVE)
step_range = np.arange(0, 20, 2)
print("np.arange(0, 20, 2):\n", step_range)

# np.linspace(start, stop, count) - count-based (stop is INCLUSIVE)
space_range = np.linspace(0, 1, 5)
print("\nnp.linspace(0, 1, 5):\n", space_range)

np.arange(0, 20, 2):
 [ 0  2  4  6  8 10 12 14 16 18]

np.linspace(0, 1, 5):
 [0.   0.25 0.5  0.75 1.  ]


### 1.3 Key Attributes & Data Types
Every NumPy array exposes metadata describing its structure, data type, and memory footprint.

| Attribute | Description |
| :--- | :--- |
| `.ndim` | Number of array dimensions (axes) |
| `.shape` | Tuple showing lengths along each dimension (rows, columns, ...) |
| `.size` | Total count of elements in the array |
| `.dtype` | The data type of stored elements (`int32`, `float64`, `bool`, etc.)

In [33]:
sample_matrix = np.array([[10, 20, 30], [40, 50, 60]])

print("Matrix:\n", sample_matrix)
print("ndim (dimensions):", sample_matrix.ndim)
print("shape:            ", sample_matrix.shape)
print("size (elements):  ", sample_matrix.size)
print("dtype:            ", sample_matrix.dtype)

Matrix:
 [[10 20 30]
 [40 50 60]]
ndim (dimensions): 2
shape:             (2, 3)
size (elements):   6
dtype:             int64


#### Explicit Type Conversion with `.astype()`
To convert an array's data type, use `.astype()`. Note that converting float to int truncates toward zero.

In [34]:
float_arr = np.array([1.2, 2.8, 3.5, 4.1])
print("Original:", float_arr, "| dtype:", float_arr.dtype)

# Cast to 64-bit integer
int_arr = float_arr.astype(np.int64)
print("Casted to int64:  ", int_arr, "| dtype:", int_arr.dtype)

# Cast to boolean (non-zero becomes True)
bool_arr = np.array([0, 1, 5, 0]).astype(bool)
print("Casted to bool:   ", bool_arr)

Original: [1.2 2.8 3.5 4.1] | dtype: float64
Casted to int64:   [1 2 3 4] | dtype: int64
Casted to bool:    [False  True  True False]


### 1.4 Indexing & Multi-Dimensional Slicing
NumPy extends Python's `[start:stop:step]` slicing notation to multiple dimensions.

Syntax for 2D arrays: `arr[row_slice, col_slice]`
- A single colon `:` selects all elements along that axis.
- `start:stop` slices from `start` index up to `stop - 1`.
- Negative indices count backwards from the end.

In [25]:
# 1D Indexing & Slicing
x = np.arange(10, 100, 10) # [10, 20, 30, 40, 50, 60, 70, 80, 90]
print("1D Array:           ", x)
print("Element at index [3]:", x[3])
print("Slice [2:6]:         ", x[2:6])
print("Every second [::2]:  ", x[::2])
print("Reversed array [::-1]:", x[::-1])

1D Array:            [10 20 30 40 50 60 70 80 90]
Element at index [3]: 40
Slice [2:6]:          [30 40 50 60]
Every second [::2]:   [10 30 50 70 90]
Reversed array [::-1]: [90 80 70 60 50 40 30 20 10]


In [26]:
# 2D Indexing & Slicing
grid = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])
print("Grid (4x4):\n", grid)

print("\nSingle element grid[1, 2]:", grid[1, 2]) # Row index 1, Col index 2 -> 23
print("First row grid[0, :]:     ", grid[0, :])
print("Second column grid[:, 1]: ", grid[:, 1])

# Slicing a submatrix (Rows 1-2, Columns 1-2)
submatrix = grid[1:3, 1:3]
print("\nSubmatrix grid[1:3, 1:3]:\n", submatrix)

Grid (4x4):
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]

Single element grid[1, 2]: 23
First row grid[0, :]:      [11 12 13 14]
Second column grid[:, 1]:  [12 22 32 42]

Submatrix grid[1:3, 1:3]:
 [[22 23]
 [32 33]]


### 1.5 The Golden Rule: Views vs. Copies
> **CRITICAL CONCEPT**: In NumPy, array slices are **views**, NOT copies!
>
> When you slice an array, the new variable points to the **exact same memory buffer** as the original. Modifying the slice modifies the original array.
> To create an independent duplicate, you must explicitly call `.copy()`.

In [ ]:
# Demonstrating the View Pitfall
original = np.array([100, 200, 300, 400, 500])
print("Original before slice modification:", original)

# Creating a slice (VIEW)
view_slice = original[1:4]
view_slice[0] = 999  # Mutating the view

print("View slice:                         ", view_slice)
print("Original AFTER view modification:   ", original)  # Index 1 is permanently modified!

# Safe approach: using .copy()
safe_original = np.array([100, 200, 300, 400, 500])
safe_copy = safe_original[1:4].copy()
safe_copy[0] = 777

print("\nSafe Original after copy modification:", safe_original) # Untouched!
print("Independent Copy:                     ", safe_copy)

### 1.6 Boolean Indexing & Conditional Filtering
Boolean indexing extracts elements that satisfy specified conditions.

Rules for boolean logic in NumPy:
- Use `&` for element-wise AND (do NOT use Python's `and` keyword)
- Use `|` for element-wise OR (do NOT use Python's `or` keyword)
- Use `~` for element-wise NOT (do NOT use Python's `not` keyword)
- **Always wrap each condition in parentheses `()`** due to Python operator precedence rules.

In [ ]:
values = np.array([15, 82, 34, 91, 10, 56, 73, 28, 49])

# 1. Create a boolean mask
mask = values > 50
print("Values:       ", values)
print("Mask (> 50):  ", mask)

# 2. Filter elements using the mask
filtered = values[mask]
print("Filtered:     ", filtered)

# 3. Compound condition: Values between 30 and 80
compound_mask = (values >= 30) & (values <= 80)
print("Values in [30, 80]:", values[compound_mask])

# 4. In-place conditional update: Cap values greater than 60 to 60
capped_values = values.copy()
capped_values[capped_values > 60] = 60
print("Values capped at 60:", capped_values)

#### Vectorized Ternary with `np.where()`
`np.where(condition, value_if_true, value_if_false)` works like an Excel `IF()` statement across all elements.

In [ ]:
exam_scores = np.array([45, 78, 92, 58, 64, 88])

# Assign 'Pass' if score >= 60, else 'Fail'
grade_results = np.where(exam_scores >= 60, "Pass", "Fail")

print("Exam Scores: ", exam_scores)
print("Grade Status:", grade_results)

### 1.7 Fancy Indexing (Integer Array Indexing)
Fancy indexing means indexing using arrays or lists of integer positions. It lets you retrieve or reorder arbitrary elements.
**Important**: Fancy indexing always produces a **copy**, not a view.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Select non-contiguous elements at indices 0, 2, 5, and 8
selected_indices = [0, 2, 5, 8]
result = arr[selected_indices]

print("Original Array:   ", arr)
print("Selected Elements:", result)

# Reordering or permuting elements
permuted = arr[[4, 0, 3, 1]]
print("Permuted:         ", permuted)

### 1.8 Vectorized Operations & Universal Functions (UFuncs)
Universal functions (UFuncs) perform fast element-wise operations on arrays at native C speed.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise Arithmetic Operators
print("a + b = ", a + b)
print("b - a = ", b - a)
print("a * b = ", a * b)
print("b / a = ", b / a)
print("a ** 3 = ", a ** 3)

# Mathematical Universal Functions
numbers = np.array([1.0, 4.0, 9.0, 16.0])
print("\nnp.sqrt:", np.sqrt(numbers))
print("np.exp: ", np.exp(np.array([0, 1, 2])))
print("np.log: ", np.log(np.array([1, np.e, np.e**2])))
print("np.abs: ", np.abs(np.array([-15, 20, -5, 0])))

### 1.9 Broadcasting Mechanics Explained
**Broadcasting** describes how NumPy handles arithmetic operations between arrays of **different shapes** without unnecessary memory duplication.

#### The 2 Compatibility Rules:
Comparing shapes element-wise from **right to left** (trailing dimensions):
1. The dimension sizes are identical, **OR**
2. One of the dimension sizes is `1` (which NumPy stretches automatically).

In [ ]:
# Case 1: Matrix + Scalar
matrix = np.ones((2, 3))
print("2x3 Matrix + 10 (Scalar broadcast):\n", matrix + 10)

# Case 2: (3, 3) Matrix + (3,) 1D Row Vector
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
row_vec = np.array([1, 2, 3])
print("\nMatrix A (3x3):\n", A)
print("Row Vector (3,):", row_vec)
print("A + row_vec (broadcast across every row):\n", A + row_vec)

# Case 3: Column Vector (3, 1) + Row Vector (1, 4) -> Broadcasts into (3, 4) Matrix!
col_vec = np.array([[10], [20], [30]])  # shape (3, 1)
row_vec2 = np.array([[1, 2, 3, 4]])     # shape (1, 4)
outer_grid = col_vec + row_vec2

print("\nCol (3x1) + Row (1x4) Result (3x4):\n", outer_grid)
print("Resulting Shape:", outer_grid.shape)

### 1.10 Aggregations & Axis-Wise Reductions
Aggregations collapse multi-dimensional data into summary statistics.

The `axis` parameter:
- `axis=None` (default): Aggregate over the **entire array** (returns a single scalar).
- `axis=0`: Collapse across rows (computes statistics for **each column**).
- `axis=1`: Collapse across columns (computes statistics for **each row**).

In [ ]:
data_matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("Data Matrix (2x3):\n", data_matrix)

print("\n--- Overall Reductions ---")
print("Sum:  ", np.sum(data_matrix))
print("Mean: ", np.mean(data_matrix))
print("Std:  ", np.std(data_matrix).round(2))
print("Min:  ", np.min(data_matrix))
print("Max:  ", np.max(data_matrix))

print("\n--- Axis-Wise Reductions ---")
# axis=0 collapses rows -> results in column sums
print("Sum along axis=0 (Column sums):", np.sum(data_matrix, axis=0))

# axis=1 collapses columns -> results in row sums
print("Sum along axis=1 (Row sums):   ", np.sum(data_matrix, axis=1))

# Finding positions of extrema
sample = np.array([25, 80, 12, 99, 43])
print("\nSample:", sample)
print("Index of Min (np.argmin):", np.argmin(sample)) # Index of 12 -> 2
print("Index of Max (np.argmax):", np.argmax(sample)) # Index of 99 -> 3
print("Cumulative Sum (cumsum): ", np.cumsum(sample))

### 1.11 Shape Manipulation, Stacking & Splitting
Reshaping and restructuring arrays is essential for preparing tensors for machine learning algorithms.

Key Functions:
- `.reshape(shape)`: Changes shape (`-1` automatically infers dimension)
- `.ravel()`: Returns flattened 1D view (memory efficient)
- `.flatten()`: Returns flattened 1D copy
- `.T`: Transpose matrix dimensions
- `np.vstack()`, `np.hstack()`: Vertical and horizontal array stacking
- `np.split()`: Splits an array into sub-arrays

In [ ]:
# Reshaping
arr_12 = np.arange(12)  # [0, 1, 2, ..., 11]
reshaped_3x4 = arr_12.reshape(3, 4)
print("Reshaped to (3, 4):\n", reshaped_3x4)

# Inferred dimension using -1
inferred = arr_12.reshape(2, -1) # 2 rows, NumPy calculates 6 columns
print("\nInferred shape (2, -1):", inferred.shape)

# Transpose (.T)
print("\nTransposed Matrix (4x3):\n", reshaped_3x4.T)

# Flattening: ravel (view) vs flatten (copy)
print("\nFlattened with ravel():", reshaped_3x4.ravel())

In [ ]:
# Stacking arrays
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Vertical stack (row-wise)
v_stacked = np.vstack((v1, v2))
print("Vertical Stack (np.vstack):\n", v_stacked)

# Horizontal stack (column-wise)
h_stacked = np.hstack((v1, v2))
print("\nHorizontal Stack (np.hstack):", h_stacked)

# Splitting an array into equal sections
split_result = np.split(np.arange(9), 3)
print("\nSplit np.arange(9) into 3 equal arrays:", split_result)

---
# Module 2: pandas Foundations

**pandas** is Python's standard library for tabular data structures, cleaning, and analytics.

### Why pandas builds on NumPy:
While NumPy provides fast array mathematics on homogeneous blocks, real-world data contains:
1. **Heterogeneous Columns** (Text, dates, integers, floats side by side in one table)
2. **Labels** (Column headers and row index identifiers)
3. **Automatic Alignment** and database-style joins

### The 2 Core Structures:
- **Series**: A 1-dimensional labeled array (a single column of data).
- **DataFrame**: A 2-dimensional labeled table composed of multiple Series sharing a common index.

### 2.2 The pandas Series: 1D Labeled Array
A Series consists of:
1. An array of **values** (underlying NumPy ndarray)
2. An **index** (labels identifying each item)

In [ ]:
# Creating a Series from a Python List with custom labels
ages = pd.Series([25, 30, 35, 40], index=["Alice", "Bob", "Charlie", "David"], name="Age")
print("pandas Series:\n", ages)

# Accessing the components
print("\nValues: ", ages.values, "| Type:", type(ages.values))
print("Index:  ", ages.index)
print("Name:   ", ages.name)

# Selecting by label and by integer position
print("\nAlice's age (by label):   ", ages["Alice"])
print("First element (by position):", ages.iloc[0])

# Vectorized operation on Series
print("\nAges + 5:\n", ages + 5)
print("\nAges > 30:\n", ages[ages > 30])

In [ ]:
# Creating a Series from a Python Dictionary
# Dictionary keys automatically become the Series index labels!
population_dict = {
    "Tokyo": 37_400_000,
    "Delhi": 30_290_000,
    "Shanghai": 27_050_000,
    "São Paulo": 22_040_000
}
city_pop = pd.Series(population_dict, name="Population")
print("Series from Dictionary:\n", city_pop)

### 2.3 Creating DataFrames
DataFrames can be initialized from various Python and NumPy data structures.

Common formats:
1. **Dictionary of Lists**: Column-oriented (each key is a column name, value is a list of column values).
2. **List of Dictionaries**: Row-oriented (typical when parsing JSON records or REST APIs).
3. **2D NumPy Array**: Providing numerical matrix with explicit `columns` and `index` arguments.

In [ ]:
# Method 1: From a Dictionary of Lists (Column-oriented)
employee_data = {
    "Employee": ["Sophia", "Liam", "Emma", "Noah", "Ava"],
    "Department": ["Engineering", "Marketing", "Engineering", "HR", "Marketing"],
    "Salary": [95000, 68000, 105000, 62000, 74000],
    "Experience_Years": [4, 3, 7, 2, 5]
}
df_employees = pd.DataFrame(employee_data)
print("DataFrame from Dict of Lists:")
print(df_employees)

In [ ]:
# Method 2: From a List of Dictionaries (Row-oriented / JSON)
product_records = [
    {"Product": "Laptop", "Price": 1200, "In_Stock": True},
    {"Product": "Mouse", "Price": 25, "In_Stock": True},
    {"Product": "Monitor", "Price": 300, "In_Stock": False}
]
df_products = pd.DataFrame(product_records)
print("DataFrame from List of Records:")
print(df_products)

# Method 3: From a 2D NumPy Array
num_matrix = np.arange(1, 10).reshape(3, 3)
df_numpy = pd.DataFrame(num_matrix, columns=["Col_A", "Col_B", "Col_C"], index=["R1", "R2", "R3"])
print("\nDataFrame from NumPy Array:")
print(df_numpy)

### 2.4 Data Exploration & Inspection Checklist
Always run this inspection checklist whenever loading or receiving a new dataset.

In [ ]:
# Structural health check
print("--- Shape (rows, columns) ---")
print(df_employees.shape)

# Column Names
print("\n--- Column Names ---")
print(df_employees.columns.tolist())

# Data Types
print("\n--- Data Types ---")
print(df_employees.dtypes)

# Concise structural summary
print("\n--- .info() (Compact Overview & Null counts) ---")
df_employees.info()

# Head
print("\n--- .head(2) (First 2 rows) ---")
print(df_employees.head(2))

# Describe
print("\n--- .describe() (Statistical distribution of numeric columns) ---")
print(df_employees.describe())

In [ ]:
# Categorical inspection
print("Department Value Counts:")
print(df_employees["Department"].value_counts())

print("\nUnique Departments:", df_employees["Department"].unique())
print("Unique Count:       ", df_employees["Department"].nunique())

### 2.5 Indexing & Selection Trifecta: `[]`, `.loc`, and `.iloc`

| Selection Method | Purpose | Syntax | Endpoint Rule |
| :--- | :--- | :--- | :--- |
| `df['col']` | Select single column as **Series** | `df['col']` | N/A |
| `df[['c1', 'c2']]` | Select multiple columns as **DataFrame** | `df[['c1', 'c2']]` | N/A |
| `.loc[]` | **Label-based** indexing for rows & columns | `df.loc[row_label, col_label]` | **Inclusive** of stop |
| `.iloc[]` | **Integer position-based** indexing | `df.iloc[row_pos, col_pos]` | **Exclusive** of stop (standard Python) |

In [ ]:
# Column Selection
# Single bracket -> Series
dept_series = df_employees["Department"]
print("Single bracket returns:", type(dept_series))

# Double bracket -> DataFrame
emp_salary_df = df_employees[["Employee", "Salary"]]
print("Double bracket returns:", type(emp_salary_df))
print(emp_salary_df)

In [ ]:
# .loc vs .iloc Deep Dive

# 1. .loc selects by LABEL (Index labels and Column names)
# Select rows 0 to 2 (INCLUSIVE!) and columns 'Employee' to 'Salary'
print(".loc Selection (by labels):")
print(df_employees.loc[0:2, "Employee":"Salary"])

# 2. .iloc selects by INTEGER POSITION (0-indexed, EXCLUSIVE stop)
# Select rows 0 to 2 (indices 0 and 1) and columns 0 to 2
print("\n.iloc Selection (by integer positions):")
print(df_employees.iloc[0:2, 0:2])

# Selecting a single scalar value at Row 1, Col 2 (Liam's Salary)
print("\nScalar at row 1, col 2 (.iloc[1, 2]):", df_employees.iloc[1, 2])

### 2.6 Conditional Filtering & Querying
Filter rows meeting logical criteria using boolean conditions or `.query()`.

In [ ]:
# 1. Simple condition: Employees earning >= 75,000
high_earners = df_employees[df_employees["Salary"] >= 75000]
print("Employees with Salary >= 75,000:")
print(high_earners)

# 2. Compound condition: Engineering AND Experience > 3
senior_engineers = df_employees[
    (df_employees["Department"] == "Engineering") &
    (df_employees["Experience_Years"] > 3)
]
print("\nSenior Engineers:")
print(senior_engineers)

# 3. Membership filtering with .isin()
target_depts = ["Marketing", "HR"]
mkt_hr_df = df_employees[df_employees["Department"].isin(target_depts)]
print("\nEmployees in Marketing or HR (.isin):")
print(mkt_hr_df)

# 4. String-based querying with .query()
queried_df = df_employees.query("Salary > 70000 and Department == 'Marketing'")
print("\nQuery result (.query):\n", queried_df)

### 2.7 Modifying DataFrames (Columns, Rows & Index Management)
Learn feature engineering, renaming, dropping columns, and changing indices.

In [ ]:
df_mod = df_employees.copy()

# 1. Adding new derived columns (Vectorized calculation)
df_mod["Monthly_Salary"] = (df_mod["Salary"] / 12).round(2)
df_mod["Bonus_Eligible"] = df_mod["Experience_Years"] >= 4

print("DataFrame with Engineered Columns:")
print(df_mod)

In [ ]:
# 2. Renaming columns with .rename(columns={...})
df_mod = df_mod.rename(columns={
    "Experience_Years": "Exp_Yrs",
    "Bonus_Eligible": "Is_Bonus_Eligible"
})
print("After Renaming:")
print(df_mod.head(2))

# 3. Dropping a column with .drop(columns=[...])
df_mod = df_mod.drop(columns=["Monthly_Salary"])
print("\nAfter Dropping 'Monthly_Salary':")
print(df_mod.head(2))

# 4. Setting and resetting the index
df_indexed = df_mod.set_index("Employee")
print("\nWith 'Employee' as Row Index:")
print(df_indexed)

# Reset back to default integer range index
df_reset = df_indexed.reset_index()
print("\nAfter reset_index():")
print(df_reset.head(2))

### 2.8 Handling Missing Data (Data Hygiene)
In pandas, missing numeric values are represented by `NaN` (`np.nan`).

Key Methods:
- `.isna()` / `.isnull()`: Returns boolean mask of missing values.
- `.isna().sum()`: Counts missing values per column.
- `.dropna()`: Drops rows or columns containing missing values.
- `.fillna(value)`: Replaces missing values with a designated constant or metric.
- `.ffill()` / `.bfill()`: Forward-fill / backward-fill values.

In [ ]:
# Constructing a DataFrame with realistic missing values
messy_df = pd.DataFrame({
    "Student": ["Alex", "Bella", "Chris", "Diana", "Evan"],
    "Math": [92, np.nan, 78, 88, np.nan],
    "English": [85, 79, np.nan, 90, 68],
    "Attendance": [95, 88, 70, np.nan, 80]
})

print("Messy Dataset with Missing Values:")
print(messy_df)

print("\nMissing Count per Column:")
print(messy_df.isna().sum())

In [ ]:
# Strategy 1: Dropping missing data
dropped_rows = messy_df.dropna()
print("After dropna() (only complete rows retained):")
print(dropped_rows)

# Drop rows only if 'Math' is missing
dropped_math = messy_df.dropna(subset=["Math"])
print("\nAfter dropna(subset=['Math']):")
print(dropped_math)

In [ ]:
# Strategy 2: Imputing missing values with statistical measures
clean_df = messy_df.copy()

# Impute missing Math score with the column average
math_mean = clean_df["Math"].mean()
clean_df["Math"] = clean_df["Math"].fillna(math_mean)

# Impute missing English score with the column median
clean_df["English"] = clean_df["English"].fillna(clean_df["English"].median())

# Forward fill Attendance
clean_df["Attendance"] = clean_df["Attendance"].ffill()

print("Cleaned & Imputed Dataset:")
print(clean_df)

### 2.9 GroupBy & Aggregations (The Split-Apply-Combine Paradigm)
The **Split-Apply-Combine** principle:
1. **Split**: Break data into distinct groups based on keys.
2. **Apply**: Compute aggregate functions (`mean`, `sum`, `count`, `min`, `max`, etc.) on each group.
3. **Combine**: Merge the results into a summary DataFrame.

In [ ]:
# Sample Sales Dataset
sales_df = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "North", "West", "South"],
    "Category": ["Tech", "Furniture", "Tech", "Office", "Tech", "Office", "Furniture", "Tech"],
    "Revenue": [1200, 450, 980, 150, 2100, 320, 800, 1450],
    "Units_Sold": [4, 2, 3, 5, 7, 4, 3, 5]
})
print("Raw Sales Transactions:")
print(sales_df)

In [ ]:
# 1. Single Grouping with Single Metric
avg_rev_by_region = sales_df.groupby("Region")["Revenue"].mean().round(2)
print("Average Revenue by Region:")
print(avg_rev_by_region)

# 2. Multiple Aggregations on a Column
region_stats = sales_df.groupby("Region")["Revenue"].agg(["count", "mean", "min", "max", "sum"])
print("\nDetailed Revenue Stats by Region:")
print(region_stats)

# 3. Multi-Column Grouping (Region AND Category)
multi_group = sales_df.groupby(["Region", "Category"])["Revenue"].sum().reset_index()
print("\nTotal Revenue by Region & Category:")
print(multi_group)

# 4. Custom Aggregation Dictionary (Different functions for different columns)
custom_agg = sales_df.groupby("Region").agg({
    "Revenue": ["sum", "mean"],
    "Units_Sold": "sum"
})
print("\nCustom Multi-Metric Aggregation:")
print(custom_agg)

### 2.10 Combining Datasets: Concatenation & Relational Merges

1. **`pd.concat([df1, df2], axis=0)`**: Stacking tables vertically (adding rows) or horizontally (`axis=1`, adding columns).
2. **`pd.merge(left, right, on='key', how='inner'|'left'|'right'|'outer')`**: Performing relational SQL database joins.

In [ ]:
# 1. Concatenation: Stacking Datasets Vertically
q1_sales = pd.DataFrame({
    "Store_ID": [101, 102],
    "Quarter": ["Q1", "Q1"],
    "Sales": [50000, 72000]
})

q2_sales = pd.DataFrame({
    "Store_ID": [101, 102, 103],
    "Quarter": ["Q2", "Q2", "Q2"],
    "Sales": [55000, 79000, 41000]
})

combined_sales = pd.concat([q1_sales, q2_sales], ignore_index=True)
print("Concatenated Sales (Q1 + Q2):\n", combined_sales)

In [ ]:
# 2. Relational Merges (SQL-Style Joins)
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "City": ["Seattle", "Chicago", "Boston", "Austin"]
})

orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004],
    "Customer_ID": [1, 2, 1, 5],  # Customer 5 is not in customers table
    "Amount": [250, 400, 150, 700]
})

# INNER JOIN: Only rows where Customer_ID matches in BOTH tables
inner_merged = pd.merge(orders, customers, on="Customer_ID", how="inner")
print("--- INNER JOIN ---")
print(inner_merged)

# LEFT JOIN: All orders retained; missing customer profiles filled with NaN
left_merged = pd.merge(orders, customers, on="Customer_ID", how="left")
print("\n--- LEFT JOIN ---")
print(left_merged)

# OUTER JOIN: All records from both tables included
outer_merged = pd.merge(orders, customers, on="Customer_ID", how="outer")
print("\n--- OUTER JOIN ---")
print(outer_merged)

### 2.11 Sorting & Ranking Data
Sort rows by column values or index labels, and compute relative ranks.

In [ ]:
df_items = pd.DataFrame({
    "Item": ["Apples", "Bananas", "Cherries", "Dates", "Elderberries"],
    "Category": ["Fruit", "Fruit", "Fruit", "Fruit", "Fruit"],
    "Stock": [50, 120, 30, 80, 15],
    "Price": [1.5, 0.8, 4.0, 3.5, 6.0]
})

# Sort by Price descending
sorted_price = df_items.sort_values(by="Price", ascending=False)
print("Sorted by Price Descending:")
print(sorted_price)

# Multi-column sorting: Category Ascending, Stock Descending
multi_sorted = df_items.sort_values(by=["Category", "Stock"], ascending=[True, False])
print("\nMulti-Column Sort:")
print(multi_sorted)

# Ranking: Highest stock gets Rank 1
df_items["Stock_Rank"] = df_items["Stock"].rank(ascending=False, method="min").astype(int)
print("\nWith Stock Rank:")
print(df_items)

### 2.12 Essential String & Datetime Foundations

#### Vectorized String Methods via `.str`
The `.str` accessor executes string manipulation across Series while gracefully skipping `NaN` entries.

In [ ]:
text_df = pd.DataFrame({
    "Raw_Email": ["  ALICE@GMAIL.COM ", "bob_builder@Yahoo.com", "CHARLIE@Outlook.com  ", np.nan],
    "Phone": ["555-123-4567", "555-987-6543", "555-000-1111", "555-222-3333"]
})
print("Original Text Data:")
print(text_df)

# Vectorized text cleaning
text_df["Clean_Email"] = text_df["Raw_Email"].str.strip().str.lower()
text_df["Is_Gmail"] = text_df["Clean_Email"].str.contains("gmail", na=False)
text_df["Area_Code"] = text_df["Phone"].str.split("-").str[0]

print("\nCleaned Text Data:")
print(text_df)

#### Datetime Methods via `pd.to_datetime()` & `.dt`
Converting strings to datetime format exposes calendar properties like year, month name, and day of week.

In [ ]:
date_df = pd.DataFrame({
    "Date_String": ["2026-01-15", "2026-03-22", "2026-07-04", "2026-11-26"],
    "Amount": [120, 450, 980, 310]
})

# Parse to datetime64[ns]
date_df["Timestamp"] = pd.to_datetime(date_df["Date_String"])

# Calendar feature extraction using .dt accessor
date_df["Year"] = date_df["Timestamp"].dt.year
date_df["Month_Name"] = date_df["Timestamp"].dt.month_name()
date_df["Day_Name"] = date_df["Timestamp"].dt.day_name()
date_df["Is_Weekend"] = date_df["Timestamp"].dt.dayofweek >= 5

print("Datetime Extracted Features:")
print(date_df)

### 2.13 File Input / Output: Reading & Writing CSV Files
- Export to CSV: Use `df.to_csv('filename.csv', index=False)`.
- Import from CSV: Use `pd.read_csv('filename.csv', parse_dates=[...])`.

In [ ]:
# Export to CSV
csv_path = "sample_sales_output.csv"
date_df.to_csv(csv_path, index=False)
print(f"File written successfully to {csv_path}.")

# Read back from CSV
reloaded_df = pd.read_csv(csv_path, parse_dates=["Timestamp"])
print("\nReloaded DataFrame from CSV:")
print(reloaded_df.head(2))
print("Timestamp dtype:", reloaded_df["Timestamp"].dtype)

---
# Module 3: Guided Capstone Project
### End-to-End Retail Analytics Case Study

Now, let's bring **both NumPy and pandas together** in an authentic analytical workflow.

#### Scenario:
You are the Lead Data Analyst for an omnichannel retail store. You will:
1. **Synthesize** 150 transaction records using **NumPy random distributions**.
2. **Clean & Sanitize** missing discount percentages.
3. **Engineer Financial Metrics** using vectorized arithmetic (Gross Revenue, Discount Amount, Net Revenue, COGS, Net Profit, Profit Margin %).
4. **Analyze Category & Channel Performance** using multi-level **GroupBy aggregations**.
5. **Identify Top VIP Customers** to report to executive management.

In [ ]:
# Step 1: Synthesize Transaction Data with NumPy RNG
rng = np.random.default_rng(seed=101)
num_txns = 150

categories = ["Electronics", "Apparel", "Home Goods", "Books"]
channels = ["Online", "In-Store"]

capstone_df = pd.DataFrame({
    "Transaction_ID": [f"TXN-{1000 + i}" for i in range(num_txns)],
    "Customer_ID": rng.choice([f"CUST-{j:03d}" for j in range(1, 26)], size=num_txns),
    "Category": rng.choice(categories, size=num_txns, p=[0.35, 0.30, 0.20, 0.15]),
    "Channel": rng.choice(channels, size=num_txns, p=[0.60, 0.40]),
    "Unit_Price": rng.uniform(15.0, 350.0, size=num_txns).round(2),
    "Quantity": rng.integers(1, 6, size=num_txns),
    "Discount_Pct": rng.choice([0.0, 0.05, 0.10, 0.20, np.nan], size=num_txns, p=[0.4, 0.2, 0.2, 0.15, 0.05])
})

print("Raw Transactions Preview:")
print(capstone_df.head())


In [ ]:
# Step 2: Data Cleaning & Hygiene
print("Missing Values per Column:")
print(capstone_df.isna().sum())

# Impute missing Discount_Pct with 0.0 (default to no discount)
capstone_df["Discount_Pct"] = capstone_df["Discount_Pct"].fillna(0.0)

# Verify zero missing values remain
assert capstone_df.isna().sum().sum() == 0
print("\nSanitation complete: All null values handled!")

In [ ]:
# Step 3: Vectorized Feature Engineering
# Gross Revenue = Unit_Price * Quantity
capstone_df["Gross_Revenue"] = (capstone_df["Unit_Price"] * capstone_df["Quantity"]).round(2)

# Discount Amount = Gross_Revenue * Discount_Pct
capstone_df["Discount_Amt"] = (capstone_df["Gross_Revenue"] * capstone_df["Discount_Pct"]).round(2)

# Net Revenue = Gross_Revenue - Discount_Amt
capstone_df["Net_Revenue"] = (capstone_df["Gross_Revenue"] - capstone_df["Discount_Amt"]).round(2)

# COGS (Cost of Goods Sold) based on industry product category benchmarks
cogs_map = {"Electronics": 0.60, "Apparel": 0.40, "Home Goods": 0.50, "Books": 0.30}
capstone_df["Cost_Ratio"] = capstone_df["Category"].map(cogs_map)
capstone_df["COGS"] = (capstone_df["Gross_Revenue"] * capstone_df["Cost_Ratio"]).round(2)

# Net Profit & Profit Margin %
capstone_df["Net_Profit"] = (capstone_df["Net_Revenue"] - capstone_df["COGS"]).round(2)
capstone_df["Profit_Margin_Pct"] = np.where(
    capstone_df["Net_Revenue"] > 0,
    ((capstone_df["Net_Profit"] / capstone_df["Net_Revenue"]) * 100).round(2),
    0.0
)

print("Enriched Transactions with Financial Metrics:")
print(capstone_df[["Transaction_ID", "Category", "Gross_Revenue", "Net_Revenue", "Net_Profit", "Profit_Margin_Pct"]].head())

In [ ]:
# Step 4: Executive Insights & Aggregations

# 1. Performance by Product Category
category_summary = capstone_df.groupby("Category").agg(
    Transactions=("Transaction_ID", "count"),
    Units_Sold=("Quantity", "sum"),
    Total_Net_Revenue=("Net_Revenue", "sum"),
    Total_Net_Profit=("Net_Profit", "sum"),
    Avg_Margin_Pct=("Profit_Margin_Pct", "mean")
).round(2).sort_values(by="Total_Net_Revenue", ascending=False)

print("=== Product Category Performance ===")
print(category_summary)

# 2. Performance by Sales Channel
channel_summary = capstone_df.groupby("Channel").agg(
    Total_Revenue=("Net_Revenue", "sum"),
    Total_Profit=("Net_Profit", "sum"),
    Avg_Order_Value=("Net_Revenue", "mean")
).round(2)

print("\n=== Sales Channel Comparison ===")
print(channel_summary)

# 3. Top 5 VIP Customers
vip_customers = capstone_df.groupby("Customer_ID").agg(
    Total_Spend=("Net_Revenue", "sum"),
    Orders_Count=("Transaction_ID", "count"),
    Avg_Order_Value=("Net_Revenue", "mean")
).round(2).sort_values(by="Total_Spend", ascending=False).head(5)

print("\n=== Top 5 VIP Customers ===")
print(vip_customers)

---
# Module 4: Summary & Quick Reference Cheat Sheet

### NumPy Quick Reference
| Operation | Syntax | Description |
| :--- | :--- | :--- |
| **Array Creation** | `np.array(list)` / `np.arange(start, stop, step)` / `np.linspace(start, stop, num)` | Create from list or numerical range |
| **Special Arrays** | `np.zeros(shape)` / `np.ones(shape)` / `np.full(shape, val)` / `np.eye(N)` | Constant or identity matrices |
| **Random** | `rng = np.random.default_rng()`; `rng.random()`, `rng.integers()`, `rng.standard_normal()` | Modern random sampling |
| **Inspection** | `arr.shape`, `arr.ndim`, `arr.dtype`, `arr.size`, `arr.nbytes` | Core structural attributes |
| **Type Casting** | `arr.astype(np.float64)` | Explicit type conversion |
| **Slicing** | `arr[row_start:row_stop, col_start:col_stop]` | Multi-dimensional views |
| **Copying** | `arr.copy()` | Explicit independent memory allocation |
| **Filtering** | `arr[(arr > a) & (arr < b)]` | Boolean mask selection |
| **Conditional** | `np.where(cond, val_if_true, val_if_false)` | Vectorized ternary operator |
| **Reductions** | `np.sum(arr, axis=0)`, `np.mean()`, `np.std()`, `np.min()`, `np.max()`, `np.argmin()` | Aggregations across axes |
| **Reshaping** | `arr.reshape(rows, cols)` / `arr.ravel()` / `arr.T` | Shape manipulation |
| **Stacking** | `np.vstack((a, b))` / `np.hstack((a, b))` / `np.concatenate((a, b), axis=0)` | Combine arrays |

---

### pandas Quick Reference
| Operation | Syntax | Description |
| :--- | :--- | :--- |
| **Creation** | `pd.DataFrame(dict_of_lists)` / `pd.Series(list, index=...)` | Instantiate tabular structures |
| **Inspection** | `df.head()`, `df.info()`, `df.describe()`, `df.shape`, `df.dtypes` | Initial health check |
| **Value Counts** | `df['col'].value_counts()`, `df['col'].nunique()` | Categorical cardinality |
| **Label Selection**| `df.loc[row_labels, col_labels]` | Select by label (inclusive) |
| **Position Selection**| `df.iloc[row_indices, col_indices]` | Select by integer position (exclusive) |
| **Filtering** | `df[(df['A'] > 5) & (df['B'] == 'X')]`, `df.query("A > 5")` | Conditional subsetting |
| **Membership** | `df[df['col'].isin(['val1', 'val2'])]` | Set membership filter |
| **Modifying** | `df['new'] = df['a'] * df['b']`, `df.drop(columns=['a'])`, `df.rename(columns={...})` | Feature engineering |
| **Index Handling**| `df.set_index('col')`, `df.reset_index()` | Manage row index |
| **Missing Values**| `df.isna().sum()`, `df.dropna(subset=[...])`, `df.fillna(value)` | Data cleaning & imputation |
| **GroupBy** | `df.groupby('col')['val'].mean()`, `df.groupby('col').agg({'v1':'sum', 'v2':'mean'})` | Split-Apply-Combine |
| **Concat** | `pd.concat([df1, df2], axis=0, ignore_index=True)` | Vertical or horizontal stacking |
| **Merge** | `pd.merge(df1, df2, on='key', how='inner'|'left'|'right'|'outer')` | Relational SQL-style joins |
| **Sorting** | `df.sort_values(by=['col1', 'col2'], ascending=[True, False])` | Value sorting |
| **String Methods**| `df['col'].str.lower()`, `df['col'].str.contains('term')` | Vectorized text handling |
| **Datetime** | `pd.to_datetime(df['date'])`, `df['date'].dt.year`, `df['date'].dt.month_name()` | Calendar extraction |
| **I/O** | `df.to_csv('file.csv', index=False)`, `pd.read_csv('file.csv')` | CSV storage and loading |

---
### Congratulations!
You have now mastered every core foundation of **NumPy** and **pandas**! You are equipped to comfortably handle exploratory data analysis (EDA), data cleaning, tabular modeling, and high-performance numerical computing.